### ISSUE TITLE
Dashboard side menu stuck in expanded state on Wazuh ova ( specific systems)

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh-virtual-machines#125]
## Description
The left sidebar menu in the Wazuh dashboard OVA version remains persistently expanded, preventing users from collapsing it. This behavior significantly impacts the usability of the interface by limiting screen space. 

![image](https://github.com/user-attachments/assets/2cf0bd14-8c88-4fcb-911d-a492f44d9099)

### Steps to Reproduce:

1. Deploy the Wazuh OVA and access the dashboard through a web browser.
2. Log in with the appropriate credentials.
3. Attempt to interact with the left sidebar menu (e.g., try to collapse or toggle it).
4. Observe that the sidebar remains in the expanded state and cannot be collapsed.
5. Open the browser’s developer tools.
6. Check the console for any error messages. Note the Bootstrap-related error that appears.

### Additionally
A related Bootstrap error is displayed in the browser console, which could be contributing to the issue. Investigating the root cause of the menu's inability to collapse and resolving the Bootstrap-related error are crucial steps to restore proper functionality to the interface.
```console
A single error about an inline script not firing due to content security policy is expected! - bootstrap.js:37  
```

**Comment by Tostti** [comment]
Upon testing we were not able to reproduce the issue. 
The side bar works as expected, and only remains locked if the option `Dock navigation` is enabled.

![Peek 2024-12-10 16-38](https://github.com/user-attachments/assets/c02e805a-8db2-4743-af3c-2aeaceeb7043)
![Peek 2024-12-10 16-39](https://github.com/user-attachments/assets/c395b426-0c35-4be2-af6d-8cf9384f9a42)

No errors were observed in the console.

**Comment by DiegoRatto** [comment]
> [!IMPORTANT]
>  Tests have been performed on **4.9.2** and **4.10.0-rc1**, as well as on another browser (Firefox) and systems, and the problem could not be reproduced. The bug is attributed to the Brave browser, which is the one on which the tests were performed. The problem is closed.
