### ISSUE TITLE
Update the GitHub runners image from latest to ubuntu-22.04 in virtual machines workflows

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-virtual-machines#129]
## Description

Due to the updates that the `latest` images of GitHub runners undergo, we must set a fixed image to avoid failures in our workflows due to updates in the mentioned image.
It is recommended to define the image `ubuntu-22.04`

## Tasks

- [x] builder_OVA.yml
- [x] packages_builder_ami.yml

## Issue related

https://github.com/wazuh/internal-devel-requests/issues/1890

**Comment by CarlosALgit** [comment]
## Update Report

I have to open the PR again because it was closed due to branch maintenance.
